# Compilatore C++
CXX=g++

# Opzioni per il compilatore
CXXFLAGS= -O3 -std=c++20 #-fsanitize=address

# Nome dell'eseguibile
TARGET=main

# Lista di tutti i file da compilare
SRCS=main.cpp \
     zmytest/test.cpp \
     zlasdtest/test.cpp \
     zlasdtest/container/container.cpp \
     zlasdtest/exercise1a/simpletest.cpp \
     zlasdtest/exercise1a/fulltest.cpp \
     zlasdtest/exercise1b/simpletest.cpp \
     zlasdtest/exercise1b/fulltest.cpp \
     zlasdtest/exercise2a/simpletest.cpp \
     zlasdtest/exercise2a/fulltest.cpp \
     zlasdtest/exercise2b/simpletest.cpp \
     zlasdtest/exercise2b/fulltest.cpp \
     zlasdtest/exercise3/simpletest.cpp \
     zlasdtest/exercise3/fulltest.cpp

# Lista di tutti i file oggetto da generare
OBJS=$(SRCS:.cpp=.o)

# Target predefinito, che genera l'eseguibile
all: $(TARGET)

# Regola per generare l'eseguibile
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(TARGET)

# Regola per compilare un file sorgente in un file oggetto
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Pulizia dei file oggetto e dell'eseguibile
clean:
	rm -f $(OBJS) $(TARGET)
